# Conda Environment Setup Instructions
#  - Using an environment.yml file with conda
#  - Key Terminal Commands:
#
#    conda env create -f environment.yml
#    conda env update --file environment.yml --prune
#    conda env export --name name_for_the_environment > environment.yml
#    conda env remove --name name_for_the_environment
#    conda env list

name: OCR_app
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - pip
  - bottleneck
  - pip:
      - numpy==1.26.3
      - opencv-python==4.9.0.80
      - opencv-contrib-python==4.9.0.80
      - openpyxl==3.0.10
      - pandas==2.1.4
      - pytesseract==0.3.10
      - pyinstaller
      - readchar==4.0.6
      - tqdm==4.65.0