# Conda Environment Setup Instructions
#  - Using an environment.yml file with conda
#  - Key Terminal Commands:
#
#    conda activate "name of the environment"
#    conda deactivate
#    conda env create -f environment.yml
#    conda env update --file environment.yml --prune
#    conda env export --name name_for_the_environment > environment.yml
#    conda env remove --name name_for_the_environment
#    conda env list

name: OCR_app
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - bottleneck
  - pip:
      - numpy
      - opencv-python
      - opencv-contrib-python
      - openpyxl
      - pandas
      - pytesseract
      - pyinstaller
      - readchar
      - tqdm